# Generated by Django 3.1.4 on 2020-12-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_sold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sold',
        ),
    ]
